name: metalink
description: URL metadata extraction package for Dart, providing rich link previews, JSON-LD, and oEmbed support.
version: 2.0.0

homepage: https://github.com/omar-hanafy/metalink
repository: https://github.com/omar-hanafy/metalink
issue_tracker: https://github.com/omar-hanafy/metalink/issues
documentation: https://github.com/omar-hanafy/metalink#readme

topics:
  - metadata
  - url
  - preview
  - link
  - metadata-extraction

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  convert_object: ^1.0.2
  crypto: ^3.0.7
  hive_ce: ^2.18.0
  html: ^0.15.4
  http: ^1.6.0
  path: ^1.9.1
  xml: ^6.6.1
dev_dependencies:
  build_runner: ^2.4.15
  lints: ^6.0.0
  mockito: ^5.4.5
  test: ^1.25.15
